version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2021
      POSTGRES_DB: nest
    networks:
      - mynetwork
networks:
  mynetwork: